// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemYonetimi;

namespace SistemYonetimi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220512113809_EmirEsgB181200011")]
    partial class EmirEsgB181200011
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemYonetimi.Models.Log", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserLoginTime")
                        .HasColumnType("datetime2");

                    b.HasKey("LogID");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
